#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, textwrap
from pathlib import Path

ap=argparse.ArgumentParser()
ap.add_argument('--input', required=True)
ap.add_argument('--output', required=True)
a=ap.parse_args()
d=json.loads(Path(a.input).read_text())
f=d['fields']['panel']
assert f['x']==0 and f['y']==0 and f['w']==720 and f['h']==408
rank=int(f['rank'])

lines=[]; A=lines.append
A('// Generated from Design/R19OpticalField.json. Do not edit by hand.')
A('import Accelerate')
A('import CoreGraphics')
A('import Foundation')
A('import SwiftUI')
A('')
A('enum R19OpticalFieldData {')
A(f'  static let width = {f["w"]}')
A(f'  static let height = {f["h"]}')
A(f'  static let rank = {rank}')
A('')
A('  struct FactorSpec: Sendable {')
A('    let leftScale: Float')
A('    let rightScale: Float')
A('    let leftB64: String')
A('    let rightB64: String')
A('  }')
A('')

def emit_array(name, arr):
    A(f'  static let {name}: [FactorSpec] = [')
    for ch in arr:
        A('    FactorSpec(')
        A(f'      leftScale: {ch["leftScale"]:.17g},')
        A(f'      rightScale: {ch["rightScale"]:.17g},')
        A('      leftB64:')
        A('        """')
        for chunk in textwrap.wrap(ch['leftB64'], 120): A('        '+chunk)
        A('        """,')
        A('      rightB64:')
        A('        """')
        for chunk in textwrap.wrap(ch['rightB64'], 120): A('        '+chunk)
        A('        """')
        A('    ),')
    A('  ]')
    A('')

emit_array('multiplyAttenuation', f['channels']['multiplyAttenuation'])
emit_array('screen', f['channels']['screen'])
A('}')
A('')
A('private enum R19OpticalFieldRenderer {')
A('  struct Images: @unchecked Sendable { let multiply: CGImage; let screen: CGImage }')
A('  static let images: Images = buildImages()')
A('')
A('  private static func decode(_ spec: R19OpticalFieldData.FactorSpec) -> ([Float], [Float]) {')
A('    func unpack(_ encoded: String, scale: Float) -> [Float] {')
A('      guard let data = Data(base64Encoded: encoded, options: [.ignoreUnknownCharacters]) else { return [] }')
A('      return data.withUnsafeBytes { raw in')
A('        let bytes = raw.bindMemory(to: UInt8.self)')
A('        var out = [Float](repeating: 0, count: bytes.count / 2)')
A('        for i in out.indices {')
A('          let lo = UInt16(bytes[i * 2])')
A('          let hi = UInt16(bytes[i * 2 + 1]) << 8')
A('          out[i] = Float(Int16(bitPattern: lo | hi)) * scale')
A('        }')
A('        return out')
A('      }')
A('    }')
A('    return (unpack(spec.leftB64, scale: spec.leftScale), unpack(spec.rightB64, scale: spec.rightScale))')
A('  }')
A('')
A('  private static func reconstruct(_ specs: [R19OpticalFieldData.FactorSpec]) -> [[Float]] {')
A('    let w = R19OpticalFieldData.width, h = R19OpticalFieldData.height, r = R19OpticalFieldData.rank')
A('    return specs.map { spec in')
A('      let (left, right) = decode(spec)')
A('      precondition(left.count == h * r && right.count == r * w, "R19 optical field factor shape mismatch")')
A('      var result = [Float](repeating: 0, count: w * h)')
A('      vDSP_mmul(left, 1, right, 1, &result, 1, vDSP_Length(h), vDSP_Length(w), vDSP_Length(r))')
A('      for i in result.indices { result[i] = min(1, max(0, result[i])) }')
A('      return result')
A('    }')
A('  }')
A('')
A('  private static func image(channels: [[Float]], multiply: Bool) -> CGImage {')
A('    let w = R19OpticalFieldData.width, h = R19OpticalFieldData.height')
A('    var pixels = [UInt8](repeating: 255, count: w * h * 4)')
A('    for i in 0..<(w * h) {')
A('      for c in 0..<3 {')
A('        let v = multiply ? (1 - channels[c][i]) : channels[c][i]')
A('        pixels[i * 4 + c] = UInt8(clamping: Int((min(1, max(0, v)) * 255).rounded()))')
A('      }')
A('      pixels[i * 4 + 3] = 255')
A('    }')
A('    let data = Data(pixels) as CFData')
A('    let provider = CGDataProvider(data: data)!')
A('    return CGImage(')
A('      width: w, height: h, bitsPerComponent: 8, bitsPerPixel: 32, bytesPerRow: w * 4,')
A('      space: CGColorSpaceCreateDeviceRGB(),')
A('      bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.last.rawValue),')
A('      provider: provider, decode: nil, shouldInterpolate: true, intent: .defaultIntent')
A('    )!')
A('  }')
A('')
A('  private static func buildImages() -> Images {')
A('    let attenuation = reconstruct(R19OpticalFieldData.multiplyAttenuation)')
A('    let screen = reconstruct(R19OpticalFieldData.screen)')
A('    return Images(multiply: image(channels: attenuation, multiply: true), screen: image(channels: screen, multiply: false))')
A('  }')
A('}')
A('')
A('struct R19OpticalFieldOverlay: View {')
A('  var body: some View {')
A('    ZStack {')
A('      Image(decorative: R19OpticalFieldRenderer.images.multiply, scale: 1, orientation: .up)')
A('        .resizable()')
A('        .interpolation(.high)')
A('        .blendMode(.multiply)')
A('      Image(decorative: R19OpticalFieldRenderer.images.screen, scale: 1, orientation: .up)')
A('        .resizable()')
A('        .interpolation(.high)')
A('        .blendMode(.screen)')
A('    }')
A('    .allowsHitTesting(false)')
A('  }')
A('}')
Path(a.output).write_text('\n'.join(lines)+'\n')
print(a.output)
